/*
  Warnings:

  - You are about to drop the column `birim_id` on the `DavetTokeni` table. All the data in the column will be lost.
  - You are about to drop the column `birim_id` on the `Kullanici` table. All the data in the column will be lost.
  - You are about to drop the `Birim` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `kategori` to the `Kurum` table without a default value. This is not possible if the table is not empty.
  - Added the required column `tip` to the `Kurum` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "KurumKategorisi" AS ENUM ('MULKI_IDARE', 'YEREL_YONETIM', 'EMNIYET_ASAYIS', 'ADALET', 'EGITIM', 'SAGLIK', 'MALIYE_VERGI', 'TAPU_KADASTRO', 'NUFUS_VATANDASLIK', 'SOSYAL_HIZMETLER', 'TARIM_ORMAN_HAYVANCILIK', 'ULASTIRMA_ALTYAPI', 'CEVRE_SEHIRCILIK_IMAR', 'AFET_ACIL_DURUM', 'KULTUR_SPOR_GENCLIK', 'DIN_HIZMETLERI', 'TICARET_SANAYI', 'ISTIHDAM', 'BANKA_FINANS', 'ASKERLIK', 'GUMRUK', 'SIVIL_TOPLUM', 'BASIN_MEDYA');

-- CreateEnum
CREATE TYPE "KurumTipi" AS ENUM ('KAYMAKAMLIK', 'YAZI_ISLERI_MUDURLUGU', 'ILCE_IDARE_KURULU', 'HUKUK_ISLERI', 'BASIN_HALKLA_ILISKILER', 'BELEDIYE_BASKANLIGI', 'BELDE_BELEDIYESI', 'KOYLERE_HIZMET_GOTURME_BIRLIGI', 'MAHALLE_MUHTARLIGI', 'KOY_MUHTARLIGI', 'ILCE_EMNIYET_MUDURLUGU', 'POLIS_MERKEZI', 'ILCE_JANDARMA_KOMUTANLIGI', 'JANDARMA_KARAKOLU', 'SAHIL_GUVENLIK_KOMUTANLIGI', 'ADLIYE', 'CUMHURIYET_BASSAVCILIGI', 'ASLIYE_HUKUK_MAHKEMESI', 'SULH_HUKUK_MAHKEMESI', 'ASLIYE_CEZA_MAHKEMESI', 'SULH_CEZA_MAHKEMESI', 'ICRA_MUDURLUGU', 'NOTERLIK', 'BARO_TEMSILCILIGI', 'CEZAEVI', 'DENETIMLI_SERBESTLIK', 'ADLI_TIP', 'ILCE_MILLI_EGITIM_MUDURLUGU', 'HALK_EGITIM_MERKEZI', 'MESLEKI_EGITIM_MERKEZI', 'REHBERLIK_ARASTIRMA_MERKEZI', 'ANAOKULU', 'ILKOKUL', 'ORTAOKUL', 'LISE', 'ANADOLU_LISESI', 'FEN_LISESI', 'IMAM_HATIP_LISESI', 'MESLEK_LISESI', 'OZEL_EGITIM_OKULU', 'OGRETMENEVI', 'KYK_YURDU', 'OZEL_YURT', 'UNIVERSITE', 'MESLEK_YUKSEKOKULU', 'ILCE_SAGLIK_MUDURLUGU', 'DEVLET_HASTANESI', 'AGIZ_DIS_SAGLIGI_MERKEZI', 'TOPLUM_SAGLIGI_MERKEZI', 'AILE_SAGLIGI_MERKEZI', 'ACIL_SAGLIK_ISTASYONU', 'VEREM_SAVAS_DISPANSERI', 'HALK_SAGLIGI_LABORATUVARI', 'OZEL_HASTANE', 'TIP_MERKEZI', 'ECZANE', 'ILCE_MAL_MUDURLUGU', 'DEFTERDARLIK', 'VERGI_DAIRESI', 'SGK_ILCE_MUDURLUGU', 'HAZINE_MALIYE', 'TAPU_MUDURLUGU', 'KADASTRO_MUDURLUGU', 'ILCE_NUFUS_MUDURLUGU', 'ILCE_SECIM_KURULU', 'GOC_IDARESI', 'SOSYAL_YARDIMLASMA_DAYANISMA_VAKFI', 'AILE_SOSYAL_HIZMETLER_ILCE_MUDURLUGU', 'COCUK_EVI', 'SEVGI_EVI', 'HUZUREVI', 'YASLI_BAKIM_MERKEZI', 'ENGELLI_BAKIM_MERKEZI', 'SIDDET_ONLEME_IZLEME_MERKEZI', 'KADIN_KONUKEVI', 'ILCE_TARIM_ORMAN_MUDURLUGU', 'ORMAN_ISLETME_SEFLIGI', 'SU_URUNLERI_SUBESI', 'VETERINER_HEKIMLIGI', 'SULAMA_BIRLIGI', 'ZIRAAT_ODASI', 'KARAYOLLARI_SUBE_SEFLIGI', 'PTT_MUDURLUGU', 'DSI_SUBESI', 'TEDAS', 'ELEKTRIK_DAGITIM', 'BOTAS', 'DOGALGAZ_DAGITIM', 'TELEKOM', 'CEVRE_SEHIRCILIK_ILCE_MUDURLUGU', 'MILLI_EMLAK_SEFLIGI', 'METEOROLOJI_ISTASYONU', 'AFAD_ILCE_BIRIMI', 'ITFAIYE', 'KIZILAY_SUBESI', 'ARAMA_KURTARMA_BIRIMI', 'ILCE_KULTUR_MUDURLUGU', 'ILCE_GENCLIK_SPOR_MUDURLUGU', 'HALK_KUTUPHANESI', 'MUZE', 'GENCLIK_MERKEZI', 'SPOR_TESISI', 'STADYUM', 'ILCE_MUFTULUGU', 'CAMI', 'KURAN_KURSU', 'TICARET_SANAYI_ODASI', 'ESNAF_SANATKARLAR_ODASI', 'TICARET_BORSASI', 'OSB_MUDURLUGU', 'KOSGEB_TEMSILCILIGI', 'ISKUR_ILCE_HIZMET_MERKEZI', 'ZIRAAT_BANKASI', 'HALKBANK', 'VAKIFBANK', 'OZEL_BANKA', 'PTT_BANK', 'KATILIM_BANKASI', 'ASKERLIK_SUBESI', 'GUMRUK_MUDURLUGU', 'GUMRUK_MUHAFAZA', 'DERNEK', 'VAKIF', 'SENDIKA', 'MESLEK_ODASI', 'YEREL_GAZETE', 'YEREL_RADYO', 'YEREL_TV', 'HABER_AJANSI');

-- CreateEnum
CREATE TYPE "KullaniciOnayDurumu" AS ENUM ('BEKLIYOR', 'ONAYLANDI', 'REDDEDILDI');

-- DropForeignKey
ALTER TABLE "Birim" DROP CONSTRAINT "Birim_kurum_id_fkey";

-- DropForeignKey
ALTER TABLE "Birim" DROP CONSTRAINT "Birim_ust_birim_id_fkey";

-- DropForeignKey
ALTER TABLE "Kullanici" DROP CONSTRAINT "Kullanici_birim_id_fkey";

-- DropIndex
DROP INDEX "Kullanici_birim_id_idx";

-- AlterTable
ALTER TABLE "DavetTokeni" DROP COLUMN "birim_id",
ADD COLUMN     "kurum_id" UUID;

-- AlterTable
ALTER TABLE "Kullanici" DROP COLUMN "birim_id",
ADD COLUMN     "onay_durumu" "KullaniciOnayDurumu" NOT NULL DEFAULT 'BEKLIYOR',
ADD COLUMN     "onay_zamani" TIMESTAMP(3),
ADD COLUMN     "onaylayan_id" UUID,
ADD COLUMN     "red_sebebi" TEXT;

-- AlterTable
ALTER TABLE "Kurum" ADD COLUMN     "kategori" "KurumKategorisi" NOT NULL,
ADD COLUMN     "silindi_mi" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "silinme_zamani" TIMESTAMP(3),
ADD COLUMN     "tip" "KurumTipi" NOT NULL,
ALTER COLUMN "ad" DROP NOT NULL;

-- DropTable
DROP TABLE "Birim";

-- CreateTable
CREATE TABLE "KartHedefKurumu" (
    "kart_id" UUID NOT NULL,
    "kurum_id" UUID NOT NULL,
    "eklenme_zamani" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "KartHedefKurumu_pkey" PRIMARY KEY ("kart_id","kurum_id")
);

-- CreateIndex
CREATE INDEX "KartHedefKurumu_kurum_id_idx" ON "KartHedefKurumu"("kurum_id");

-- CreateIndex
CREATE INDEX "Kullanici_onay_durumu_idx" ON "Kullanici"("onay_durumu");

-- CreateIndex
CREATE INDEX "Kurum_kategori_idx" ON "Kurum"("kategori");

-- CreateIndex
CREATE INDEX "Kurum_tip_idx" ON "Kurum"("tip");

-- CreateIndex
CREATE INDEX "Kurum_silindi_mi_idx" ON "Kurum"("silindi_mi");

-- AddForeignKey
ALTER TABLE "KartHedefKurumu" ADD CONSTRAINT "KartHedefKurumu_kart_id_fkey" FOREIGN KEY ("kart_id") REFERENCES "Kart"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "KartHedefKurumu" ADD CONSTRAINT "KartHedefKurumu_kurum_id_fkey" FOREIGN KEY ("kurum_id") REFERENCES "Kurum"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
