import type { KurumKategorisi, KurumTipi } from "@prisma/client";

export const KURUM_KATEGORI_LABEL: Record<KurumKategorisi, string> = {
  MULKI_IDARE: "Mülki İdare",
  YEREL_YONETIM: "Yerel Yönetim",
  EMNIYET_ASAYIS: "Emniyet & Asayiş",
  ADALET: "Adalet",
  EGITIM: "Eğitim",
  SAGLIK: "Sağlık",
  MALIYE_VERGI: "Maliye & Vergi",
  TAPU_KADASTRO: "Tapu & Kadastro",
  NUFUS_VATANDASLIK: "Nüfus & Vatandaşlık",
  SOSYAL_HIZMETLER: "Sosyal Hizmetler",
  TARIM_ORMAN_HAYVANCILIK: "Tarım, Orman & Hayvancılık",
  ULASTIRMA_ALTYAPI: "Ulaştırma & Altyapı",
  CEVRE_SEHIRCILIK_IMAR: "Çevre, Şehircilik & İmar",
  AFET_ACIL_DURUM: "Afet & Acil Durum",
  KULTUR_SPOR_GENCLIK: "Kültür, Spor & Gençlik",
  DIN_HIZMETLERI: "Din Hizmetleri",
  TICARET_SANAYI: "Ticaret & Sanayi",
  ISTIHDAM: "İstihdam",
  BANKA_FINANS: "Banka & Finans",
  ASKERLIK: "Askerlik",
  GUMRUK: "Gümrük",
  SIVIL_TOPLUM: "Sivil Toplum",
  BASIN_MEDYA: "Basın & Medya",
};

export const KURUM_TIP_LABEL: Record<KurumTipi, string> = {
  // MULKI_IDARE
  KAYMAKAMLIK: "Kaymakamlık",
  OZEL_KALEM: "Özel Kalem",
  YAZI_ISLERI_MUDURLUGU: "Yazı İşleri Müdürlüğü",
  ILCE_IDARE_KURULU: "İlçe İdare Kurulu",
  HUKUK_ISLERI: "Hukuk İşleri",
  BASIN_HALKLA_ILISKILER: "Basın ve Halkla İlişkiler",

  // YEREL_YONETIM
  BELEDIYE_BASKANLIGI: "Belediye Başkanlığı",
  BELDE_BELEDIYESI: "Belde Belediyesi",
  KOYLERE_HIZMET_GOTURME_BIRLIGI: "Köylere Hizmet Götürme Birliği",
  MAHALLE_MUHTARLIGI: "Mahalle Muhtarlığı",
  KOY_MUHTARLIGI: "Köy Muhtarlığı",

  // EMNIYET_ASAYIS
  ILCE_EMNIYET_MUDURLUGU: "İlçe Emniyet Müdürlüğü",
  POLIS_MERKEZI: "Polis Merkezi",
  ILCE_JANDARMA_KOMUTANLIGI: "İlçe Jandarma Komutanlığı",
  JANDARMA_KARAKOLU: "Jandarma Karakolu",
  SAHIL_GUVENLIK_KOMUTANLIGI: "Sahil Güvenlik Komutanlığı",

  // ADALET
  ADLIYE: "Adliye",
  CUMHURIYET_BASSAVCILIGI: "Cumhuriyet Başsavcılığı",
  ASLIYE_HUKUK_MAHKEMESI: "Asliye Hukuk Mahkemesi",
  SULH_HUKUK_MAHKEMESI: "Sulh Hukuk Mahkemesi",
  ASLIYE_CEZA_MAHKEMESI: "Asliye Ceza Mahkemesi",
  SULH_CEZA_MAHKEMESI: "Sulh Ceza Mahkemesi",
  ICRA_MUDURLUGU: "İcra Müdürlüğü",
  NOTERLIK: "Noterlik",
  BARO_TEMSILCILIGI: "Baro Temsilciliği",
  CEZAEVI: "Cezaevi",
  DENETIMLI_SERBESTLIK: "Denetimli Serbestlik",
  ADLI_TIP: "Adli Tıp",

  // EGITIM
  ILCE_MILLI_EGITIM_MUDURLUGU: "İlçe Milli Eğitim Müdürlüğü",
  HALK_EGITIM_MERKEZI: "Halk Eğitim Merkezi",
  MESLEKI_EGITIM_MERKEZI: "Mesleki Eğitim Merkezi",
  REHBERLIK_ARASTIRMA_MERKEZI: "Rehberlik ve Araştırma Merkezi",
  ANAOKULU: "Anaokulu",
  ILKOKUL: "İlkokul",
  ORTAOKUL: "Ortaokul",
  LISE: "Lise",
  ANADOLU_LISESI: "Anadolu Lisesi",
  FEN_LISESI: "Fen Lisesi",
  IMAM_HATIP_LISESI: "İmam Hatip Lisesi",
  MESLEK_LISESI: "Meslek Lisesi",
  OZEL_EGITIM_OKULU: "Özel Eğitim Okulu",
  OGRETMENEVI: "Öğretmenevi",
  KYK_YURDU: "KYK Yurdu",
  OZEL_YURT: "Özel Yurt",
  UNIVERSITE: "Üniversite",
  MESLEK_YUKSEKOKULU: "Meslek Yüksekokulu",

  // SAGLIK
  ILCE_SAGLIK_MUDURLUGU: "İlçe Sağlık Müdürlüğü",
  DEVLET_HASTANESI: "Devlet Hastanesi",
  AGIZ_DIS_SAGLIGI_MERKEZI: "Ağız ve Diş Sağlığı Merkezi",
  TOPLUM_SAGLIGI_MERKEZI: "Toplum Sağlığı Merkezi",
  AILE_SAGLIGI_MERKEZI: "Aile Sağlığı Merkezi",
  ACIL_SAGLIK_ISTASYONU: "Acil Sağlık İstasyonu",
  VEREM_SAVAS_DISPANSERI: "Verem Savaş Dispanseri",
  HALK_SAGLIGI_LABORATUVARI: "Halk Sağlığı Laboratuvarı",
  OZEL_HASTANE: "Özel Hastane",
  TIP_MERKEZI: "Tıp Merkezi",
  ECZANE: "Eczane",

  // MALIYE_VERGI
  ILCE_MAL_MUDURLUGU: "İlçe Mal Müdürlüğü",
  DEFTERDARLIK: "Defterdarlık",
  VERGI_DAIRESI: "Vergi Dairesi",
  SGK_ILCE_MUDURLUGU: "SGK İlçe Müdürlüğü",
  HAZINE_MALIYE: "Hazine ve Maliye",

  // TAPU_KADASTRO
  TAPU_MUDURLUGU: "Tapu Müdürlüğü",
  KADASTRO_MUDURLUGU: "Kadastro Müdürlüğü",

  // NUFUS_VATANDASLIK
  ILCE_NUFUS_MUDURLUGU: "İlçe Nüfus Müdürlüğü",
  ILCE_SECIM_KURULU: "İlçe Seçim Kurulu",
  GOC_IDARESI: "Göç İdaresi",

  // SOSYAL_HIZMETLER
  SOSYAL_YARDIMLASMA_DAYANISMA_VAKFI: "Sosyal Yardımlaşma ve Dayanışma Vakfı",
  AILE_SOSYAL_HIZMETLER_ILCE_MUDURLUGU:
    "Aile ve Sosyal Hizmetler İlçe Müdürlüğü",
  COCUK_EVI: "Çocuk Evi",
  SEVGI_EVI: "Sevgi Evi",
  HUZUREVI: "Huzurevi",
  YASLI_BAKIM_MERKEZI: "Yaşlı Bakım Merkezi",
  ENGELLI_BAKIM_MERKEZI: "Engelli Bakım Merkezi",
  SIDDET_ONLEME_IZLEME_MERKEZI: "Şiddet Önleme ve İzleme Merkezi",
  KADIN_KONUKEVI: "Kadın Konukevi",

  // TARIM_ORMAN_HAYVANCILIK
  ILCE_TARIM_ORMAN_MUDURLUGU: "İlçe Tarım ve Orman Müdürlüğü",
  ORMAN_ISLETME_SEFLIGI: "Orman İşletme Şefliği",
  SU_URUNLERI_SUBESI: "Su Ürünleri Şubesi",
  VETERINER_HEKIMLIGI: "Veteriner Hekimliği",
  SULAMA_BIRLIGI: "Sulama Birliği",
  ZIRAAT_ODASI: "Ziraat Odası",

  // ULASTIRMA_ALTYAPI
  KARAYOLLARI_SUBE_SEFLIGI: "Karayolları Şube Şefliği",
  PTT_MUDURLUGU: "PTT Müdürlüğü",
  DSI_SUBESI: "DSİ Şubesi",
  TEDAS: "TEDAŞ",
  ELEKTRIK_DAGITIM: "Elektrik Dağıtım",
  BOTAS: "BOTAŞ",
  DOGALGAZ_DAGITIM: "Doğalgaz Dağıtım",
  TELEKOM: "Telekom",

  // CEVRE_SEHIRCILIK_IMAR
  CEVRE_SEHIRCILIK_ILCE_MUDURLUGU: "Çevre, Şehircilik İlçe Müdürlüğü",
  MILLI_EMLAK_SEFLIGI: "Milli Emlak Şefliği",
  METEOROLOJI_ISTASYONU: "Meteoroloji İstasyonu",

  // AFET_ACIL_DURUM
  AFAD_ILCE_BIRIMI: "AFAD İlçe Birimi",
  ITFAIYE: "İtfaiye",
  KIZILAY_SUBESI: "Kızılay Şubesi",
  ARAMA_KURTARMA_BIRIMI: "Arama Kurtarma Birimi",

  // KULTUR_SPOR_GENCLIK
  ILCE_KULTUR_MUDURLUGU: "İlçe Kültür Müdürlüğü",
  ILCE_GENCLIK_SPOR_MUDURLUGU: "İlçe Gençlik ve Spor Müdürlüğü",
  HALK_KUTUPHANESI: "Halk Kütüphanesi",
  MUZE: "Müze",
  GENCLIK_MERKEZI: "Gençlik Merkezi",
  SPOR_TESISI: "Spor Tesisi",
  STADYUM: "Stadyum",

  // DIN_HIZMETLERI
  ILCE_MUFTULUGU: "İlçe Müftülüğü",
  CAMI: "Cami",
  KURAN_KURSU: "Kuran Kursu",

  // TICARET_SANAYI
  TICARET_SANAYI_ODASI: "Ticaret ve Sanayi Odası",
  ESNAF_SANATKARLAR_ODASI: "Esnaf ve Sanatkârlar Odası",
  TICARET_BORSASI: "Ticaret Borsası",
  OSB_MUDURLUGU: "OSB Müdürlüğü",
  KOSGEB_TEMSILCILIGI: "KOSGEB Temsilciliği",

  // ISTIHDAM
  ISKUR_ILCE_HIZMET_MERKEZI: "İŞKUR İlçe Hizmet Merkezi",

  // BANKA_FINANS
  ZIRAAT_BANKASI: "Ziraat Bankası",
  HALKBANK: "Halkbank",
  VAKIFBANK: "Vakıfbank",
  OZEL_BANKA: "Özel Banka",
  PTT_BANK: "PTT Bank",
  KATILIM_BANKASI: "Katılım Bankası",

  // ASKERLIK
  ASKERLIK_SUBESI: "Askerlik Şubesi",

  // GUMRUK
  GUMRUK_MUDURLUGU: "Gümrük Müdürlüğü",
  GUMRUK_MUHAFAZA: "Gümrük Muhafaza",

  // SIVIL_TOPLUM
  DERNEK: "Dernek",
  VAKIF: "Vakıf",
  SENDIKA: "Sendika",
  MESLEK_ODASI: "Meslek Odası",

  // BASIN_MEDYA
  YEREL_GAZETE: "Yerel Gazete",
  YEREL_RADYO: "Yerel Radyo",
  YEREL_TV: "Yerel TV",
  HABER_AJANSI: "Haber Ajansı",
};

export const KURUM_TIP_KATEGORI: Record<KurumTipi, KurumKategorisi> = {
  // MULKI_IDARE
  KAYMAKAMLIK: "MULKI_IDARE",
  OZEL_KALEM: "MULKI_IDARE",
  YAZI_ISLERI_MUDURLUGU: "MULKI_IDARE",
  ILCE_IDARE_KURULU: "MULKI_IDARE",
  HUKUK_ISLERI: "MULKI_IDARE",
  BASIN_HALKLA_ILISKILER: "MULKI_IDARE",

  // YEREL_YONETIM
  BELEDIYE_BASKANLIGI: "YEREL_YONETIM",
  BELDE_BELEDIYESI: "YEREL_YONETIM",
  KOYLERE_HIZMET_GOTURME_BIRLIGI: "YEREL_YONETIM",
  MAHALLE_MUHTARLIGI: "YEREL_YONETIM",
  KOY_MUHTARLIGI: "YEREL_YONETIM",

  // EMNIYET_ASAYIS
  ILCE_EMNIYET_MUDURLUGU: "EMNIYET_ASAYIS",
  POLIS_MERKEZI: "EMNIYET_ASAYIS",
  ILCE_JANDARMA_KOMUTANLIGI: "EMNIYET_ASAYIS",
  JANDARMA_KARAKOLU: "EMNIYET_ASAYIS",
  SAHIL_GUVENLIK_KOMUTANLIGI: "EMNIYET_ASAYIS",

  // ADALET
  ADLIYE: "ADALET",
  CUMHURIYET_BASSAVCILIGI: "ADALET",
  ASLIYE_HUKUK_MAHKEMESI: "ADALET",
  SULH_HUKUK_MAHKEMESI: "ADALET",
  ASLIYE_CEZA_MAHKEMESI: "ADALET",
  SULH_CEZA_MAHKEMESI: "ADALET",
  ICRA_MUDURLUGU: "ADALET",
  NOTERLIK: "ADALET",
  BARO_TEMSILCILIGI: "ADALET",
  CEZAEVI: "ADALET",
  DENETIMLI_SERBESTLIK: "ADALET",
  ADLI_TIP: "ADALET",

  // EGITIM
  ILCE_MILLI_EGITIM_MUDURLUGU: "EGITIM",
  HALK_EGITIM_MERKEZI: "EGITIM",
  MESLEKI_EGITIM_MERKEZI: "EGITIM",
  REHBERLIK_ARASTIRMA_MERKEZI: "EGITIM",
  ANAOKULU: "EGITIM",
  ILKOKUL: "EGITIM",
  ORTAOKUL: "EGITIM",
  LISE: "EGITIM",
  ANADOLU_LISESI: "EGITIM",
  FEN_LISESI: "EGITIM",
  IMAM_HATIP_LISESI: "EGITIM",
  MESLEK_LISESI: "EGITIM",
  OZEL_EGITIM_OKULU: "EGITIM",
  OGRETMENEVI: "EGITIM",
  KYK_YURDU: "EGITIM",
  OZEL_YURT: "EGITIM",
  UNIVERSITE: "EGITIM",
  MESLEK_YUKSEKOKULU: "EGITIM",

  // SAGLIK
  ILCE_SAGLIK_MUDURLUGU: "SAGLIK",
  DEVLET_HASTANESI: "SAGLIK",
  AGIZ_DIS_SAGLIGI_MERKEZI: "SAGLIK",
  TOPLUM_SAGLIGI_MERKEZI: "SAGLIK",
  AILE_SAGLIGI_MERKEZI: "SAGLIK",
  ACIL_SAGLIK_ISTASYONU: "SAGLIK",
  VEREM_SAVAS_DISPANSERI: "SAGLIK",
  HALK_SAGLIGI_LABORATUVARI: "SAGLIK",
  OZEL_HASTANE: "SAGLIK",
  TIP_MERKEZI: "SAGLIK",
  ECZANE: "SAGLIK",

  // MALIYE_VERGI
  ILCE_MAL_MUDURLUGU: "MALIYE_VERGI",
  DEFTERDARLIK: "MALIYE_VERGI",
  VERGI_DAIRESI: "MALIYE_VERGI",
  SGK_ILCE_MUDURLUGU: "MALIYE_VERGI",
  HAZINE_MALIYE: "MALIYE_VERGI",

  // TAPU_KADASTRO
  TAPU_MUDURLUGU: "TAPU_KADASTRO",
  KADASTRO_MUDURLUGU: "TAPU_KADASTRO",

  // NUFUS_VATANDASLIK
  ILCE_NUFUS_MUDURLUGU: "NUFUS_VATANDASLIK",
  ILCE_SECIM_KURULU: "NUFUS_VATANDASLIK",
  GOC_IDARESI: "NUFUS_VATANDASLIK",

  // SOSYAL_HIZMETLER
  SOSYAL_YARDIMLASMA_DAYANISMA_VAKFI: "SOSYAL_HIZMETLER",
  AILE_SOSYAL_HIZMETLER_ILCE_MUDURLUGU: "SOSYAL_HIZMETLER",
  COCUK_EVI: "SOSYAL_HIZMETLER",
  SEVGI_EVI: "SOSYAL_HIZMETLER",
  HUZUREVI: "SOSYAL_HIZMETLER",
  YASLI_BAKIM_MERKEZI: "SOSYAL_HIZMETLER",
  ENGELLI_BAKIM_MERKEZI: "SOSYAL_HIZMETLER",
  SIDDET_ONLEME_IZLEME_MERKEZI: "SOSYAL_HIZMETLER",
  KADIN_KONUKEVI: "SOSYAL_HIZMETLER",

  // TARIM_ORMAN_HAYVANCILIK
  ILCE_TARIM_ORMAN_MUDURLUGU: "TARIM_ORMAN_HAYVANCILIK",
  ORMAN_ISLETME_SEFLIGI: "TARIM_ORMAN_HAYVANCILIK",
  SU_URUNLERI_SUBESI: "TARIM_ORMAN_HAYVANCILIK",
  VETERINER_HEKIMLIGI: "TARIM_ORMAN_HAYVANCILIK",
  SULAMA_BIRLIGI: "TARIM_ORMAN_HAYVANCILIK",
  ZIRAAT_ODASI: "TARIM_ORMAN_HAYVANCILIK",

  // ULASTIRMA_ALTYAPI
  KARAYOLLARI_SUBE_SEFLIGI: "ULASTIRMA_ALTYAPI",
  PTT_MUDURLUGU: "ULASTIRMA_ALTYAPI",
  DSI_SUBESI: "ULASTIRMA_ALTYAPI",
  TEDAS: "ULASTIRMA_ALTYAPI",
  ELEKTRIK_DAGITIM: "ULASTIRMA_ALTYAPI",
  BOTAS: "ULASTIRMA_ALTYAPI",
  DOGALGAZ_DAGITIM: "ULASTIRMA_ALTYAPI",
  TELEKOM: "ULASTIRMA_ALTYAPI",

  // CEVRE_SEHIRCILIK_IMAR
  CEVRE_SEHIRCILIK_ILCE_MUDURLUGU: "CEVRE_SEHIRCILIK_IMAR",
  MILLI_EMLAK_SEFLIGI: "CEVRE_SEHIRCILIK_IMAR",
  METEOROLOJI_ISTASYONU: "CEVRE_SEHIRCILIK_IMAR",

  // AFET_ACIL_DURUM
  AFAD_ILCE_BIRIMI: "AFET_ACIL_DURUM",
  ITFAIYE: "AFET_ACIL_DURUM",
  KIZILAY_SUBESI: "AFET_ACIL_DURUM",
  ARAMA_KURTARMA_BIRIMI: "AFET_ACIL_DURUM",

  // KULTUR_SPOR_GENCLIK
  ILCE_KULTUR_MUDURLUGU: "KULTUR_SPOR_GENCLIK",
  ILCE_GENCLIK_SPOR_MUDURLUGU: "KULTUR_SPOR_GENCLIK",
  HALK_KUTUPHANESI: "KULTUR_SPOR_GENCLIK",
  MUZE: "KULTUR_SPOR_GENCLIK",
  GENCLIK_MERKEZI: "KULTUR_SPOR_GENCLIK",
  SPOR_TESISI: "KULTUR_SPOR_GENCLIK",
  STADYUM: "KULTUR_SPOR_GENCLIK",

  // DIN_HIZMETLERI
  ILCE_MUFTULUGU: "DIN_HIZMETLERI",
  CAMI: "DIN_HIZMETLERI",
  KURAN_KURSU: "DIN_HIZMETLERI",

  // TICARET_SANAYI
  TICARET_SANAYI_ODASI: "TICARET_SANAYI",
  ESNAF_SANATKARLAR_ODASI: "TICARET_SANAYI",
  TICARET_BORSASI: "TICARET_SANAYI",
  OSB_MUDURLUGU: "TICARET_SANAYI",
  KOSGEB_TEMSILCILIGI: "TICARET_SANAYI",

  // ISTIHDAM
  ISKUR_ILCE_HIZMET_MERKEZI: "ISTIHDAM",

  // BANKA_FINANS
  ZIRAAT_BANKASI: "BANKA_FINANS",
  HALKBANK: "BANKA_FINANS",
  VAKIFBANK: "BANKA_FINANS",
  OZEL_BANKA: "BANKA_FINANS",
  PTT_BANK: "BANKA_FINANS",
  KATILIM_BANKASI: "BANKA_FINANS",

  // ASKERLIK
  ASKERLIK_SUBESI: "ASKERLIK",

  // GUMRUK
  GUMRUK_MUDURLUGU: "GUMRUK",
  GUMRUK_MUHAFAZA: "GUMRUK",

  // SIVIL_TOPLUM
  DERNEK: "SIVIL_TOPLUM",
  VAKIF: "SIVIL_TOPLUM",
  SENDIKA: "SIVIL_TOPLUM",
  MESLEK_ODASI: "SIVIL_TOPLUM",

  // BASIN_MEDYA
  YEREL_GAZETE: "BASIN_MEDYA",
  YEREL_RADYO: "BASIN_MEDYA",
  YEREL_TV: "BASIN_MEDYA",
  HABER_AJANSI: "BASIN_MEDYA",
};

export const KURUM_KATEGORI_TIPLER: Record<KurumKategorisi, KurumTipi[]> =
  Object.entries(KURUM_TIP_KATEGORI).reduce(
    (acc, [tip, kategori]) => {
      (acc[kategori] ??= []).push(tip as KurumTipi);
      return acc;
    },
    {} as Record<KurumKategorisi, KurumTipi[]>,
  );

export function kurumTipininKategorisi(tip: KurumTipi): KurumKategorisi {
  return KURUM_TIP_KATEGORI[tip];
}

/**
 * Tekil kurum tipleri: ilçede genelde 1 tane bulunur, `ad` opsiyoneldir
 * (görüntülenirken `KURUM_TIP_LABEL[tip]` kullanılır). Seed verisi otomatik
 * olarak bu tiplerden tek satır üretir.
 *
 * Çoklu tipler (ECZANE, ILKOKUL, CAMI vb.) bu sette yer almaz; onlarda `ad`
 * zorunludur ve kullanıcı/seed tarafından elle eklenir.
 */
export const KURUM_TIP_TEKIL: ReadonlySet<KurumTipi> = new Set<KurumTipi>([
  // MULKI_IDARE
  "KAYMAKAMLIK",
  "OZEL_KALEM",
  "YAZI_ISLERI_MUDURLUGU",
  "ILCE_IDARE_KURULU",
  "HUKUK_ISLERI",
  "BASIN_HALKLA_ILISKILER",

  // YEREL_YONETIM (sadece kaymakamlığın bağlı olduğu ilçenin kendi belediyesi)
  "BELEDIYE_BASKANLIGI",
  "KOYLERE_HIZMET_GOTURME_BIRLIGI",

  // EMNIYET_ASAYIS
  "ILCE_EMNIYET_MUDURLUGU",
  "ILCE_JANDARMA_KOMUTANLIGI",
  "SAHIL_GUVENLIK_KOMUTANLIGI",

  // ADALET
  "ADLIYE",
  "CUMHURIYET_BASSAVCILIGI",
  "ICRA_MUDURLUGU",
  "BARO_TEMSILCILIGI",
  "DENETIMLI_SERBESTLIK",
  "ADLI_TIP",

  // EGITIM
  "ILCE_MILLI_EGITIM_MUDURLUGU",
  "HALK_EGITIM_MERKEZI",
  "MESLEKI_EGITIM_MERKEZI",
  "REHBERLIK_ARASTIRMA_MERKEZI",
  "OGRETMENEVI",

  // SAGLIK
  "ILCE_SAGLIK_MUDURLUGU",
  "TOPLUM_SAGLIGI_MERKEZI",
  "VEREM_SAVAS_DISPANSERI",
  "HALK_SAGLIGI_LABORATUVARI",

  // MALIYE_VERGI
  "ILCE_MAL_MUDURLUGU",
  "DEFTERDARLIK",
  "SGK_ILCE_MUDURLUGU",
  "HAZINE_MALIYE",

  // TAPU_KADASTRO
  "TAPU_MUDURLUGU",
  "KADASTRO_MUDURLUGU",

  // NUFUS_VATANDASLIK
  "ILCE_NUFUS_MUDURLUGU",
  "ILCE_SECIM_KURULU",
  "GOC_IDARESI",

  // SOSYAL_HIZMETLER
  "SOSYAL_YARDIMLASMA_DAYANISMA_VAKFI",
  "AILE_SOSYAL_HIZMETLER_ILCE_MUDURLUGU",
  "SIDDET_ONLEME_IZLEME_MERKEZI",
  "KADIN_KONUKEVI",

  // TARIM_ORMAN_HAYVANCILIK
  "ILCE_TARIM_ORMAN_MUDURLUGU",
  "ZIRAAT_ODASI",

  // ULASTIRMA_ALTYAPI
  "PTT_MUDURLUGU",

  // CEVRE_SEHIRCILIK_IMAR
  "CEVRE_SEHIRCILIK_ILCE_MUDURLUGU",
  "MILLI_EMLAK_SEFLIGI",

  // AFET_ACIL_DURUM
  "AFAD_ILCE_BIRIMI",
  "KIZILAY_SUBESI",

  // KULTUR_SPOR_GENCLIK
  "ILCE_KULTUR_MUDURLUGU",
  "ILCE_GENCLIK_SPOR_MUDURLUGU",

  // DIN_HIZMETLERI
  "ILCE_MUFTULUGU",

  // TICARET_SANAYI
  "TICARET_SANAYI_ODASI",
  "ESNAF_SANATKARLAR_ODASI",
  "TICARET_BORSASI",

  // ISTIHDAM
  "ISKUR_ILCE_HIZMET_MERKEZI",

  // ASKERLIK
  "ASKERLIK_SUBESI",
]);

export function kurumTekilMi(tip: KurumTipi): boolean {
  return KURUM_TIP_TEKIL.has(tip);
}

export function kurumGorunenAd(kurum: {
  ad: string | null;
  tip: KurumTipi;
}): string {
  return kurum.ad ?? KURUM_TIP_LABEL[kurum.tip];
}
