export const IZIN_ANAHTARLARI = [
  // Sistem & Yönetim
  'dizge.ayarlar',
  'dizge.denetim',
  'dizge.izin_yonet',
  'dizge.istisna_yonet',
  'dizge.tatil_yonet',
  'dizge.kalip_yonet',
  'dizge.atama_kurali_yonet',
  'rapor.oku.tumu',
  'rapor.oku.birim',
  // Birim & Kullanıcı
  'birim.olustur',
  'birim.duzenle',
  'birim.sil',
  'birim.uye.oku',
  'kullanici.olustur',
  'kullanici.duzenle',
  'kullanici.sil',
  'kullanici.devre_disi_birak',
  // Proje
  'proje.olustur',
  'proje.duzenle',
  'proje.uye_ekle',
  'proje.uye_onayla',
  'proje.kapatma_iste',
  'proje.kapat',
  'proje.arsivle',
  'proje.oku.tumu',
  'proje.oku.uye_oldugu',
  // Görev
  'gorev.olustur',
  'gorev.olustur.ozel',
  'gorev.duzenle.kendi',
  'gorev.duzenle.tumu',
  'gorev.ata',
  'gorev.yeniden_ata',
  'gorev.iptal',
  'gorev.sil',
  'gorev.onaya_sun',
  'gorev.onayla',
  'gorev.reddet',
  'gorev.altgorev.olustur',
  'gorev.baglilik.duzenle',
  'gorev.izle',
  'gorev.toplu.islem',
  // Yorum & Derkenar
  'yorum.olustur',
  'yorum.duzenle.kendi',
  'yorum.sil.kendi',
  'yorum.sil.tumu',
  'derkenar.olustur',
  'derkenar.duzenle.kendi',
  'derkenar.duzenle.tumu',
  'derkenar.sabitle',
  'derkenar.surum.oku',
  // Vekâlet
  'vekalet.olustur',
  'vekalet.geri_al.kendi',
  'vekalet.geri_al.tumu',
  'vekalet.oku.tumu',
  // Bildirim
  'bildirim.tercih.duzenle',
  'bildirim.oku.kendi',
  // Dosya
  'dosya.yukle',
  'dosya.indir',
  'dosya.sil.kendi',
  'dosya.sil.tumu',
  // Arama
  'arama.kullan',
] as const

export type IzinAnahtari = (typeof IZIN_ANAHTARLARI)[number]
