// ADR-0014 / Sprint 3 S3-5 — Sistem rolleri için varsayılan izin paketi.
// Seed bu matrisi DB'ye uygular. UI'da kullanıcı bunları değiştirebilir.

import { IzinKategorisi } from "@prisma/client";
import { ROL_KODLARI } from "../roller";
import { IZIN_KODLARI, type IzinKodu, TUM_IZIN_KODLARI } from "./kodlar";
import { IZIN_KATEGORI } from "./kategori";

const TUM_PROJE_IZINLERI: IzinKodu[] = [
  IZIN_KODLARI.PROJE_OLUSTUR,
  IZIN_KODLARI.PROJE_AD_DUZENLE,
  IZIN_KODLARI.PROJE_ACIKLAMA_DUZENLE,
  IZIN_KODLARI.PROJE_KAPAK_RENK,
  IZIN_KODLARI.PROJE_KAPAK_IKON,
  IZIN_KODLARI.PROJE_YILDIZLA,
  IZIN_KODLARI.PROJE_ARSIVLE,
  IZIN_KODLARI.PROJE_SIL,
  IZIN_KODLARI.PROJE_GERI_YUKLE,
  IZIN_KODLARI.PROJE_SIRALA,
  IZIN_KODLARI.PROJE_YETKILI_LISTELE,
  IZIN_KODLARI.PROJE_YETKILI_KISI_ATA,
  IZIN_KODLARI.PROJE_YETKILI_KISI_CIKAR,
  IZIN_KODLARI.PROJE_YETKILI_BIRIM_ATA,
  IZIN_KODLARI.PROJE_YETKILI_BIRIM_CIKAR,
  IZIN_KODLARI.PROJE_YETKILI_DAVET_GONDER,
];

const TUM_LISTE_IZINLERI: IzinKodu[] = [
  IZIN_KODLARI.LISTE_OLUSTUR,
  IZIN_KODLARI.LISTE_AD_DUZENLE,
  IZIN_KODLARI.LISTE_SIRALA,
  IZIN_KODLARI.LISTE_ARSIVLE,
  IZIN_KODLARI.LISTE_SIL,
  IZIN_KODLARI.LISTE_GERI_YUKLE,
  IZIN_KODLARI.LISTE_YETKILI_LISTELE,
  IZIN_KODLARI.LISTE_YETKILI_KISI_ATA,
  IZIN_KODLARI.LISTE_YETKILI_KISI_CIKAR,
  IZIN_KODLARI.LISTE_YETKILI_BIRIM_ATA,
  IZIN_KODLARI.LISTE_YETKILI_BIRIM_CIKAR,
];

const TUM_KART_IZINLERI: IzinKodu[] = TUM_IZIN_KODLARI.filter(
  (k) => IZIN_KATEGORI[k] === IzinKategorisi.KART,
);

const TUM_DOSYA_IZINLERI: IzinKodu[] = TUM_IZIN_KODLARI.filter(
  (k) => IZIN_KATEGORI[k] === IzinKategorisi.DOSYA,
);

// ADR-0028 — PERSONEL temel dosya işleri yapabilir; gizlilik/kalıcı silme
// /güvenlik yönetimi/dışa aktarma yetkili rollere bırakılır.
const PERSONEL_DOSYA: IzinKodu[] = [
  IZIN_KODLARI.DOSYA_OKU,
  IZIN_KODLARI.DOSYA_YUKLE,
  IZIN_KODLARI.DOSYA_INDIR,
  IZIN_KODLARI.DOSYA_ONIZLE,
  IZIN_KODLARI.DOSYA_AD_DUZENLE,
  IZIN_KODLARI.DOSYA_ACIKLAMA_DUZENLE,
  IZIN_KODLARI.DOSYA_ETIKET_ATA,
  IZIN_KODLARI.DOSYA_BAGLANTI_EKLE,
  IZIN_KODLARI.DOSYA_SURUM_YUKLE,
  IZIN_KODLARI.DOSYA_KENDI_SIL,
];

const BIRIM_AMIRI_DOSYA: IzinKodu[] = [
  ...PERSONEL_DOSYA,
  IZIN_KODLARI.DOSYA_GIZLILIK_DUZENLE,
  IZIN_KODLARI.DOSYA_ETIKET_YONET,
  IZIN_KODLARI.DOSYA_BAGLANTI_KALDIR,
  IZIN_KODLARI.DOSYA_BASKA_SIL,
  IZIN_KODLARI.DOSYA_GERI_YUKLE,
  IZIN_KODLARI.DOSYA_TOPLU_ISLEM,
  IZIN_KODLARI.DOSYA_DISA_AKTAR,
];

// PERSONEL için "iş yapan" minimum: kart yaz + yorum + eklenti + checklist madde işaretle.
// KART_TAMAMLA ADR-0018 ile çıkarıldı — sadece SUPER_ADMIN + KAYMAKAM kart kapatabilir.
const PERSONEL_KART: IzinKodu[] = [
  IZIN_KODLARI.KART_OLUSTUR,
  IZIN_KODLARI.KART_BASLIK_DUZENLE,
  IZIN_KODLARI.KART_ACIKLAMA_DUZENLE,
  IZIN_KODLARI.KART_TASI,
  IZIN_KODLARI.KART_KAPAK_RENK,
  IZIN_KODLARI.KART_TARIH_BASLANGIC,
  IZIN_KODLARI.KART_TARIH_BITIS,
  IZIN_KODLARI.KART_ETIKET_ATA,
  IZIN_KODLARI.KART_ETIKET_CIKAR,
  IZIN_KODLARI.KART_YORUM_OKU,
  IZIN_KODLARI.KART_YORUM_YAZ,
  IZIN_KODLARI.KART_YORUM_KENDI_DUZENLE,
  IZIN_KODLARI.KART_YORUM_KENDI_SIL,
  IZIN_KODLARI.KART_EKLENTI_OKU,
  IZIN_KODLARI.KART_EKLENTI_YUKLE,
  IZIN_KODLARI.KART_EKLENTI_INDIR,
  IZIN_KODLARI.KART_EKLENTI_KENDI_SIL,
  IZIN_KODLARI.KART_KONTROL_MADDE_ISARETLE,
];

// Sprint 4 / S4-17 — Dead izinler (KART_KOPYALA, KART_ILISKI_KUR,
// KART_ILISKI_KALDIR) varsayılan rol izin listelerinden kaldırıldı.
// Karar: katalog'da TANIM olarak kalır (gelecek feature implement
// edilirken yeniden eklenir); seed/varsayılan atamadan çıkarıldı —
// kullanıcılar var olmayan eylemler için izinli görünmesin.
// Detay: ADR-0033.
const BIRIM_AMIRI_KART: IzinKodu[] = [
  ...PERSONEL_KART,
  IZIN_KODLARI.KART_ARSIVLE,
  IZIN_KODLARI.KART_SIL,
  IZIN_KODLARI.KART_GERI_YUKLE,
  IZIN_KODLARI.KART_KAPAK_GORSEL,
  IZIN_KODLARI.KART_ETIKET_OLUSTUR,
  IZIN_KODLARI.KART_ETIKET_DUZENLE,
  IZIN_KODLARI.KART_ETIKET_SIL,
  IZIN_KODLARI.KART_YORUM_BASKA_SIL,
  IZIN_KODLARI.KART_EKLENTI_BASKA_SIL,
  IZIN_KODLARI.KART_KONTROL_OLUSTUR,
  IZIN_KODLARI.KART_KONTROL_DUZENLE,
  IZIN_KODLARI.KART_KONTROL_SIL,
  IZIN_KODLARI.KART_KONTROL_MADDE_OLUSTUR,
  IZIN_KODLARI.KART_KONTROL_MADDE_DUZENLE,
  IZIN_KODLARI.KART_KONTROL_MADDE_SIL,
  IZIN_KODLARI.KART_YETKILI_LISTELE,
  IZIN_KODLARI.KART_YETKILI_KISI_ATA,
  IZIN_KODLARI.KART_YETKILI_KISI_CIKAR,
  IZIN_KODLARI.KART_YETKILI_BIRIM_ATA,
  IZIN_KODLARI.KART_YETKILI_BIRIM_CIKAR,
];

export const VARSAYILAN_ROL_IZINLERI: Record<string, IzinKodu[]> = {
  [ROL_KODLARI.SUPER_ADMIN]: TUM_IZIN_KODLARI,
  [ROL_KODLARI.KAYMAKAM]: [
    ...TUM_PROJE_IZINLERI,
    ...TUM_LISTE_IZINLERI,
    ...TUM_KART_IZINLERI,
    ...TUM_DOSYA_IZINLERI,
    IZIN_KODLARI.KULLANICI_DAVET_GONDER,
    IZIN_KODLARI.KULLANICI_DAVET_IPTAL,
    IZIN_KODLARI.KULLANICI_DAVET_YENIDEN,
    IZIN_KODLARI.KULLANICI_ONAYLA,
    IZIN_KODLARI.KULLANICI_REDDET,
    IZIN_KODLARI.KULLANICI_DUZENLE,
    IZIN_KODLARI.KULLANICI_PAROLA_SIFIRLA,
    IZIN_KODLARI.BIRIM_OLUSTUR,
    IZIN_KODLARI.BIRIM_DUZENLE,
    IZIN_KODLARI.BIRIM_HIYERARSI,
    IZIN_KODLARI.BIRIM_SIL,
    IZIN_KODLARI.BIRIM_GERI_YUKLE,
    IZIN_KODLARI.ROL_OLUSTUR,
    IZIN_KODLARI.ROL_DUZENLE,
    IZIN_KODLARI.ROL_IZIN_ATA,
    IZIN_KODLARI.ROL_COGALT,
    IZIN_KODLARI.ROL_SIL,
    IZIN_KODLARI.ROL_KULLANICIYA_ATA,
    IZIN_KODLARI.AKTIVITE_OKU,
    IZIN_KODLARI.AKTIVITE_DISA_AKTAR,
  ],
  [ROL_KODLARI.BIRIM_AMIRI]: [
    IZIN_KODLARI.PROJE_OLUSTUR,
    IZIN_KODLARI.PROJE_AD_DUZENLE,
    IZIN_KODLARI.PROJE_ACIKLAMA_DUZENLE,
    IZIN_KODLARI.PROJE_KAPAK_RENK,
    IZIN_KODLARI.PROJE_KAPAK_IKON,
    IZIN_KODLARI.PROJE_YILDIZLA,
    IZIN_KODLARI.PROJE_ARSIVLE,
    IZIN_KODLARI.PROJE_SIRALA,
    IZIN_KODLARI.PROJE_YETKILI_LISTELE,
    IZIN_KODLARI.PROJE_YETKILI_KISI_ATA,
    IZIN_KODLARI.PROJE_YETKILI_KISI_CIKAR,
    IZIN_KODLARI.PROJE_YETKILI_BIRIM_ATA,
    IZIN_KODLARI.PROJE_YETKILI_BIRIM_CIKAR,
    IZIN_KODLARI.PROJE_YETKILI_DAVET_GONDER,
    ...TUM_LISTE_IZINLERI,
    ...BIRIM_AMIRI_KART,
    ...BIRIM_AMIRI_DOSYA,
    IZIN_KODLARI.KULLANICI_DAVET_GONDER,
    IZIN_KODLARI.KULLANICI_DAVET_IPTAL,
    IZIN_KODLARI.KULLANICI_DAVET_YENIDEN,
    IZIN_KODLARI.AKTIVITE_OKU,
  ],
  [ROL_KODLARI.PERSONEL]: [
    ...PERSONEL_KART,
    ...PERSONEL_DOSYA,
    IZIN_KODLARI.AKTIVITE_OKU,
  ],
};
